#!/usr/bin/env python3
"""Generate a README gallery from wallpaper theme directories."""

from html import escape
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
README = ROOT / "README.md"
IMAGE_EXTENSIONS = {".avif", ".bmp", ".gif", ".jpeg", ".jpg", ".png", ".webp"}
COLUMNS = 3


def title(value: str) -> str:
    return value.replace("-", " ").replace("_", " ").title()


def image_cell(path: Path) -> str:
    relative_path = path.relative_to(ROOT).as_posix()
    url = escape(quote(relative_path, safe="/"), quote=True)
    name = escape(path.stem.replace("-", " ").replace("_", " "), quote=True)
    return f'<td><a href="{url}"><img alt="{name}" src="{url}"></a></td>'


def gallery(images: list[Path]) -> list[str]:
    lines = ["<table>"]

    for start in range(0, len(images), COLUMNS):
        row = [image_cell(image) for image in images[start : start + COLUMNS]]
        lines.append("  <tr>" + "".join(row) + "</tr>")

    lines.append("</table>")
    return lines


def main() -> None:
    themes: list[tuple[Path, list[Path]]] = []

    for directory in sorted(ROOT.iterdir(), key=lambda path: path.name.casefold()):
        if (
            not directory.is_dir()
            or directory.name.startswith(".")
            or directory.name == "archive"
            or directory.name == "source"
        ):
            continue

        images = sorted(
            (
                path
                for path in directory.rglob("*")
                if path.is_file()
                and path.suffix.lower() in IMAGE_EXTENSIONS
                and not path.stem.casefold().endswith("-colorful")
            ),
            key=lambda path: path.as_posix().casefold(),
        )
        if images:
            themes.append((directory, images))

    lines = [
        "# Wallpapers",
        "",
        "<!-- Generated by generate_readme.py. Do not edit manually. -->",
        "",
    ]

    for index, (directory, images) in enumerate(themes):
        if index:
            lines.append("")
        lines.extend([f"## {title(directory.name)}", ""])
        lines.extend(gallery(images))

    README.write_text("\n".join(lines) + "\n", encoding="utf-8")
    wallpaper_count = sum(len(images) for _, images in themes)
    print(
        f"Generated {README.name} with {wallpaper_count} wallpapers across {len(themes)} themes."
    )


if __name__ == "__main__":
    main()
