#!/usr/bin/env python3
"""Generate a README gallery from wallpaper theme directories."""

from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
README = ROOT / "README.md"
IMAGE_EXTENSIONS = {".avif", ".bmp", ".gif", ".jpeg", ".jpg", ".png", ".webp"}
COLUMNS = 3


def title(value: str) -> str:
    return value.replace("-", " ").replace("_", " ").title()


def image_link(path: Path) -> str:
    relative_path = path.relative_to(ROOT).as_posix()
    url = quote(relative_path, safe="/")
    name = path.stem.replace("-", " ").replace("_", " ")
    return f"[![{name}]({url})]({url})"


def gallery(images: list[Path]) -> list[str]:
    lines = ["| " + " | ".join(["Wallpaper"] * COLUMNS) + " |"]
    lines.append("| " + " | ".join(["---"] * COLUMNS) + " |")

    for start in range(0, len(images), COLUMNS):
        row = [image_link(image) for image in images[start : start + COLUMNS]]
        row.extend([""] * (COLUMNS - len(row)))
        lines.append("| " + " | ".join(row) + " |")

    return lines


def main() -> None:
    themes: list[tuple[Path, list[Path]]] = []

    for directory in sorted(ROOT.iterdir(), key=lambda path: path.name.casefold()):
        if (
            not directory.is_dir()
            or directory.name.startswith(".")
            or directory.name == "archive"
            or directory.name == "source"
        ):
            continue

        images = sorted(
            (
                path
                for path in directory.rglob("*")
                if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS
            ),
            key=lambda path: path.as_posix().casefold(),
        )
        if images:
            themes.append((directory, images))

    lines = [
        "# Wallpapers",
        "",
        "<!-- Generated by generate_readme.py. Do not edit manually. -->",
        "",
    ]

    for index, (directory, images) in enumerate(themes):
        if index:
            lines.append("")
        lines.extend([f"## {title(directory.name)}", ""])
        lines.extend(gallery(images))

    README.write_text("\n".join(lines) + "\n", encoding="utf-8")
    wallpaper_count = sum(len(images) for _, images in themes)
    print(
        f"Generated {README.name} with {wallpaper_count} wallpapers across {len(themes)} themes."
    )


if __name__ == "__main__":
    main()
